[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = [
  'cd ../..',
  'npm install',
  'npm run build:packages',
  'cd apps/backend',
  'npm install'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'node dist/main.js'
